[package]
name = "4x8matrix/rbxsound"
version = "1.0.2"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml", "LICENCE"]

[dependencies]
Signal = "sleitnick/signal@1.2.1"
promise = "evaera/promise@4.0.0"
sift = "csqrl/sift@0.0.4"