[package]
name = "asyncmatrix/rbxsound"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
Signal = "sleitnick/signal@1.2.1"
promise = "evaera/promise@4.0.0"
sift = "csqrl/sift@0.0.4"